# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    helper.imageresizer:
        class: Rexi\DashBoardBundle\Helper\ImageResizer

    redirect.after.login:
        class: Common\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]
    
    redirect.after.logout:
        class: Common\UserBundle\Redirection\AfterLogoutRedirection
        arguments: [@router, @security.context]