services:
    user_mailer:
        class: Common\UserBundle\Mailer\UserMailer
        arguments: [@mailer, "admin@rexi.pl", "Rexi Admin"]
        
    user_manager:
        class: Common\UserBundle\Manager\UserManager
        arguments: [@doctrine, @router, @templating, @security.encoder_factory, @user_mailer]
    userbundle.tblprefix_subscriber:
        class: Common\UserBundle\Subscriber\TablePrefixSubscriber
        arguments: [%userbundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
        
parameters:
    userbundle.db.table_prefix: rexi_