<?php

namespace Rexi\BlocksValuationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InwestycjeRepository extends EntityRepository
{
    public function getQueryBuilder(array $params = array()){
        $qb = $this->createQueryBuilder('i')
                        ->select("i.id, u.email, u.username, concat(info.imie, ' ', info.nazwisko) AS imie_nazwisko, concat(i.miasto, ' ul.', i. ulica) AS adres")
                ->leftJoin('i.id_user', 'u')         
                ->leftJoin('u.info', 'info');           
        return $qb;
    }
    
    public function getInwestycjaOtwarteUser($user_id){
        $qb = $this->createQueryBuilder('i')
                ->select("i")
                ->andWhere('i.id_user = :id_user')->setParameter('id_user', $user_id)         
                ->andWhere('i.zakonczone = :zakonczone')->setParameter('zakonczone', FALSE);  
        return $qb->setMaxResults(1)->getQuery()->getOneOrNullResult();
    }
}